# Building (não mexa a menos que saiba o que está fazendo)
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Parâmetros do site
title: "DevFest Norte 2014"
email: "mfandrade@gmail.com"
description: "DevFest Norte é o maior evento de tecnologias Google na região norte do Brasil."
baseurl: ""
url: "http://norte.devfest.com.br"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"

# Informações dos organizadores
organizerName: "GDG Belém"
organizerAlternateName: "Google Developer Group Belém"
organizerDescription: "Comunidade aberta e voluntária que estuda, cria e dissemina tecnologias e desenvolvimento ágil em Belém do Pará."
organizerEmail: "mfandrade@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://norte.devfest.com.br/"

# Metadados para a página
metaKeywords: "evento, gdg, devfest, norte, amazonia, brasil, google, programacao, android, chrome, desenvolvimento, trilha, mobile, web"
twitterAccount: "@tasafo"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documentos-chave
c4pUrl: "https://docs.google.com/forms/d/1PucWMWW3v6eGz9RQW0_q13cob45yOj6pgQ5uyq0EzYs/viewform?c=0&w=1&usp=mail_form_link"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"

# Navegação
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Agenda"}
 - {permalink: "/speakers/", text: "Palestrantes"}
 - {permalink: "/team/", text: "Equipe"}
 - {permalink: "/logistics/", text: "Logística"}
bottomNavigationLinks:
 - {link: "https://docs.google.com/forms/d/1PucWMWW3v6eGz9RQW0_q13cob45yOj6pgQ5uyq0EzYs/viewform?c=0&w=1&usp=mail_form_link", text: "Submeta sua palestra"}
rightNavigationButtons:
 - {link: "https://docs.google.com/forms/d/1PucWMWW3v6eGz9RQW0_q13cob45yOj6pgQ5uyq0EzYs/viewform?c=0&w=1&usp=mail_form_link", text: "Submeta sua palestra"}

# Bloco "Hero"
heroTitle: "DevFest Norte 2014"
eventDate: "1º de novembro de 2014" 
typeoutTextValues: '""'
typeoutFallback: "Temporada"
heroButtons:
 - {url: "https://docs.google.com/forms/d/1PucWMWW3v6eGz9RQW0_q13cob45yOj6pgQ5uyq0EzYs/viewform?c=0&w=1&usp=mail_form_link", text: "Seja um palestrante"}

# Bloco "Sobre"
aboutTitle: "Sobre o DevFest Norte"
aboutBlock:
 - {title: "Conferência", image: "conference.jpg", text: "O maior evento de tecnologias Google no norte do Brasil, conduzido por pessoas engajadas das comunidades GDG de Belém, Manaus e São Luiz!  Temas interessantes, ótimos palestrantes e muita diversão!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Um dia inteiro de workshops, experiências mão-na-massa, hacking e aprendizado. Venha e domine as tecnologias que fazem a diferença no seu dia-a-dia." }
 - {title: "Hackathon", image: "hackathon.jpg", text: "Uma verdadeira maratona de programação. Quer acumular experiência e resolver problemas do mundo real passando um dia trocando ideias e programando com pessoas que fazem a diferença?  Forme sua equipe e junte-se a nós no Hackathon!" }

# Bloco "Estatísticas"
statisticBlock:
 - {count: "250", specialCharacter: "+", info: "participantes", detail: "de todos os lugares"}
 - {count: "12", specialCharacter: "+", info: "horas", detail: "de conteúdo sobre tecnologias Google"}
 - {count: "10", specialCharacter: "+", info: "palestrantes", detail: "especialistas regionais"}
 - {count: "2", specialCharacter: "", info: "trilhas simultâneas", detail: "mais espaço para networking"}

# Bloco "Últimas Notícias"
latestNewsTitle: "Ultimas notícias"

# Bloco "Palestrantes Rockstar"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Palestrantes 'rockstar'"
rockstarSpeakersButtonText: "Veja todos os palestrantes"

# Bloco "Localização"
locationBlockTitle: "Local"
eventLocationName: "Computer Hall"
eventLocationLink: "http://www.computerhall.com.br/hall/"
eventStreetAddress: "Av. Antônio Barreto nº 1176 (entre 9 de Janeiro e Alcindo Cacela), Umarizal"
eventAddressLocality: "Belém"
eventAddressLocalityRegion: "Pará"
eventPostalCode: "66055-050"
eventAddressCountry: "Brasil"
eventStartTime: "2014-11-01T08:30"
eventDoorTime: "09:00"
eventEndTime: "2014-11-01T18:00"
eventPlaceCoordinates: "-1.4430633,-48.4779501"
mapCenterCoordinates: "-1.4430633,-48.4779501"
mapMobileCenterCoordinates: "-1.4430633,-48.4779501"

# Bloco "Venue"
venueBlockTitle: "Local"
venueTitle: "Computer Hall"
venueFeatures: ["Auditório duplo com capacidade total para 580 lugares", "6 salas de eventos", "Acesso facilitado no centro da cidade"]

# Bloco "Tweets"
tweetsFeedTitle: "O que está rolando?"
twitterHashTag: "devfestnorte"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900"

# Bloco "Parceiros"
organizersTitle: "Organizadores"
partnersTitle: "Parceiros"
partnersC4sponsorsButton: "Seja um patrocinador"

# Bloco "Subscreva-se"
subscribeTitle: "Subscreva-se para novidades"
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registre-se até a data do evento. Vagas limitadas. Fique ligado!"

# Bloco "Tíquetes"
ticketsTitle: "Tabela de preços"
ticketsInfo: "Inscrições dão acesso a todas as trilhas de palestras, material do evento e coffee-breaks. Almoço e despesas com happy-hour não inclusas."
ticketsOffers:
 -
  name: "Promocional (até 20/set)"
  price: "R$ 20,00"
  priceCurrency: "BRL"
  ticketsNumber: "200"
  featured: true
  ribbon: "-50%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Garanta agora!"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-01T10:00"
  validThrough: "2014-09-20T23:59"
 -
  name: "Normal"
  price: "R$ 40,00"
  priceCurrency: "BRL"
  ticketsNumber: "100"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Garanta o seu"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-09-21T00:00"
  validThrough: "2014-11-01T23:59"
  disabled: true

# Rodapé
socialLinks:
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
 - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdg.org.ua", text: "GDG.org.ua"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contatos"
  links:
   - {link: "mailto:comunidadetasafo@gmail.com", text: "Escreva-nos"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Código de Conduta"}

# Blog
blogTitle: "Últimas notícias"
blogCommentsEnabled: true
discusShortName: "devfestnorte"

# Bloco "Lista de Palestrantes"
showSessions: true
thumbnailsFolder: /img/speakers/

# Bloco "Equipe"
teamBlockTitle: "Quem somos"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"

# Logistics Direction Details Block
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards: 
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   - 
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
